version: '3.9'
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      AWS_SECURITY_TOKEN: ${AWS_SECURITY_TOKEN:-}
    command: >
        bash -c "cd /code/test
        && go test"
    volumes:
      - .:/code
