version: '3.9'
services:
  localstack:
    image: localstack/localstack
    hostname: localstack
    environment:
      SERVICES: s3
  go:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: mock_aws_access_key_id
      AWS_SECRET_ACCESS_KEY: mock_aws_secret_access_key
    command: >
        bash -c "cd /code/test
        && go test"
    volumes:
      - .:/code
    depends_on:
      - localstack
